import Head from 'next/head'
import React, { useEffect } from 'react'
import ProductsFeed from '../src/components/ProductsFeed'
import { getBooksAPI, getPromotionsAPI } from './api/booksApi'
import { useDispatch } from 'react-redux'
import { addPromotions } from '../src/app/slices/promotionSlice'
import { useSelector } from 'react-redux'

export default function Home({ books, promotions }) {
	const dispatch = useDispatch()
	useEffect(() => {
		dispatch(addPromotions(promotions))
	}, [1])

	const promo = useSelector((state) => state.promotions)

	const booksPromotionIntersect = () => {

	}


	return (
		<div className="mx-1 sm:mx-10">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className='text-2xl'>{promo.map((p) => {p.id})}aaa</div>
			<main className="mt-5 flex flex-col justify-center items-center">
				<ProductsFeed books={books} />
			</main>
		</div>
	)
}

export async function getServerSideProps() {
	const booksData = await getBooksAPI().then((res) => res.data)
	const promotionsData = await getPromotionsAPI().then((res) => res.data)

	return {
		props: {
			books: booksData,
			promotions: promotionsData,
		},
	}
}

// const response = await (
// 	await fetch('http://localhost:8000/books', {
// 		method: 'GET',
// 		headers: {
// 			'Content-Type': 'application/json',
// 		},
// 		body: JSON.stringify(data),
// 	})
// )
// 	.then((response) => response.json())
// 	.catch((error) => console.error('Error: ', error))
// 	.then((response) => console.log('Success:', JSON.stringify(response)))
// const data = await response.json()
